from conans import ConanFile, CMake, tools
from conans.tools import download, unzip
import os, re

class h5ppConan(ConanFile):
    name = "h5pp"
    version = "0.4.6"
    license = "MIT"
    url = "https://github.com/DavidAce/h5pp"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake_paths"
    requires = "eigen/3.3.7@conan-dmrg/patched", "spdlog/1.4.2@bincrafters/stable", "hdf5/1.10.5"
    build_policy    = 'missing'
    options         = {
        'shared': [True, False],
    }
    default_options = (
        'shared=False',
    )


    def source(self):
        zip_name = self.version+".zip"
        download("https://github.com/DavidAce/h5pp/archive/v"+self.version+".zip", zip_name)
        unzip(zip_name)
    # def source(self):
    #     self.run("git clone https://github.com/DavidAce/h5pp.git")
    #     self.run("cd h5pp")


    def build(self):
        cmake = CMake(self)
        cmake.definitions["CMAKE_TOOLCHAIN_FILE"] = "conan_paths.cmake" #generated by cmake_path generator
        cmake.definitions["ENABLE_TESTS:BOOL"] = True
        cmake.definitions["BUILD_EXAMPLES:BOOL"] = False
        cmake.definitions["BUILD_SHARED_LIBS:BOOL"] = False
        cmake.definitions['Eigen3_ROOT:PATH'] = os.path.join(self.deps_cpp_info['eigen'].rootpath)
        cmake.definitions['Eigen3_DIR:PATH'] = os.path.join(self.deps_cpp_info['eigen'].rootpath)
        cmake.definitions['EIGEN3_NO_DEFAULT_PATH:BOOL'] = True
        cmake.definitions['EIGEN3_NO_CONFIG:BOOL'] = True
        cmake.definitions['hdf5_DIR:PATH'] = os.path.join(self.deps_cpp_info['hdf5'].rootpath)
        cmake.definitions['HDF5_ROOT:PATH'] = os.path.join(self.deps_cpp_info['hdf5'].rootpath)
        cmake.definitions['SPDLOG_NO_DEFAULT_PATH:BOOL'] = True
        cmake.definitions['SPDLOG_ROOT:PATH']= os.path.join(self.deps_cpp_info['spdlog'].rootpath)
        cmake.definitions['spdlog_DIR:PATH']= os.path.join(self.deps_cpp_info['spdlog'].rootpath)
        if tools.os_info.is_linux:
            cmake.definitions['BUILD_SHARED_LIBS:BOOL'] = True if self.options.shared else False

        cmake.configure( source_folder=self.build_folder+'/h5pp-'+self.version )
        cmake.build()
        cmake.test()
        cmake.install()

    def package_id(self):
        self.info.header_only()
